version: "3"
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:v0.33.3
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./data/metabase_data:/metabase-data
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:11.5
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:4.13
    ports:
      - 8000:80
    volumes:
      - ./data/pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: metabase@example.com
      PGADMIN_DEFAULT_PASSWORD: metabase
    depends_on:
      - postgres
